// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package productreview

import (
	"context"
	"sync"
	"tlkm-api/internal/model/productreview"
)

// Ensure, that RepositoryMock does implement Repository.
// If this is not the case, regenerate this file with moq.
var _ Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked Repository
//		mockedRepository := &RepositoryMock{
//			CreateProductReviewFunc: func(ctx context.Context, req productreview.ProductReview) (productreview.ProductReviewResponse, error) {
//				panic("mock out the CreateProductReview method")
//			},
//		}
//
//		// use mockedRepository in code that requires Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// CreateProductReviewFunc mocks the CreateProductReview method.
	CreateProductReviewFunc func(ctx context.Context, req productreview.ProductReview) (productreview.ProductReviewResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateProductReview holds details about calls to the CreateProductReview method.
		CreateProductReview []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req productreview.ProductReview
		}
	}
	lockCreateProductReview sync.RWMutex
}

// CreateProductReview calls CreateProductReviewFunc.
func (mock *RepositoryMock) CreateProductReview(ctx context.Context, req productreview.ProductReview) (productreview.ProductReviewResponse, error) {
	if mock.CreateProductReviewFunc == nil {
		panic("RepositoryMock.CreateProductReviewFunc: method is nil but Repository.CreateProductReview was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req productreview.ProductReview
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockCreateProductReview.Lock()
	mock.calls.CreateProductReview = append(mock.calls.CreateProductReview, callInfo)
	mock.lockCreateProductReview.Unlock()
	return mock.CreateProductReviewFunc(ctx, req)
}

// CreateProductReviewCalls gets all the calls that were made to CreateProductReview.
// Check the length with:
//
//	len(mockedRepository.CreateProductReviewCalls())
func (mock *RepositoryMock) CreateProductReviewCalls() []struct {
	Ctx context.Context
	Req productreview.ProductReview
} {
	var calls []struct {
		Ctx context.Context
		Req productreview.ProductReview
	}
	mock.lockCreateProductReview.RLock()
	calls = mock.calls.CreateProductReview
	mock.lockCreateProductReview.RUnlock()
	return calls
}
