app:
  name: "tlkm-api"
  httpPort: "8080"
  shutdownTimeout: 10
  logLevel: PROD

postgre:
  telkom:
    read: "postgres://root:cimanggis123@localhost:5432/postgres?sslmode=disable"
    write: "postgres://root:cimanggis123@localhost:5432/postgres?sslmode=disable"

timeout_http:
  read: 5
  write: 15